// HTML Download - Best for all languages, user can print as PDF
export const exportAsHTML = async (title, content, language, type) => {
    try {
        let cleanContent = content;
        
        // Remove garbage characters
        cleanContent = cleanContent.replace(/[^\x20-\x7E\u0900-\u097F\u0980-\u09FF\n\r]/g, ' ');
        cleanContent = cleanContent.replace(/\s+/g, ' ');
        
        const htmlContent = `<!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>${title}</title>
            <style>
                body {
                    font-family: 'Segoe UI', 'Arial', 'Noto Sans Devanagari', sans-serif;
                    padding: 40px;
                    max-width: 800px;
                    margin: 0 auto;
                    line-height: 1.6;
                }
                h1 {
                    color: #9b59b6;
                    text-align: center;
                    border-bottom: 2px solid #9b59b6;
                    padding-bottom: 10px;
                }
                .metadata {
                    text-align: center;
                    color: #666;
                    font-size: 12px;
                    margin: 20px 0;
                }
                .content {
                    margin: 30px 0;
                    white-space: pre-wrap;
                    font-size: 14px;
                }
                .footer {
                    text-align: center;
                    color: #999;
                    font-size: 10px;
                    border-top: 1px solid #ddd;
                    padding-top: 20px;
                    margin-top: 40px;
                }
                @media print {
                    body {
                        padding: 20px;
                    }
                }
            </style>
        </head>
        <body>
            <h1>Vishwa Vani</h1>
            <p style="text-align: center; color: #666;">AI Document Intelligence</p>
            <h2>${title}</h2>
            <div class="metadata">
                ${type} | ${language} | ${new Date().toLocaleDateString()}
            </div>
            <div class="content">
                ${cleanContent.replace(/\n/g, '<br/>')}
            </div>
            <div class="footer">
                Generated by Vishwa Vani AI
            </div>
            <script>
                window.onload = () => {
                    setTimeout(() => {
                        if (confirm("Click OK to print/save as PDF")) {
                            window.print();
                        }
                    }, 500);
                }
            </script>
        </body>
        </html>`;
        
        const blob = new Blob([htmlContent], { type: 'text/html' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${title.replace(/[^a-zA-Z0-9]/g, '_')}.html`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        
        alert('File downloaded as HTML. Open in browser → Ctrl+P → Save as PDF for best results!');
        return true;
    } catch (error) {
        console.error('Export Error:', error);
        alert('Error creating file');
        return false;
    }
};