import html2pdf from 'html2pdf.js';

export const exportProfessionalPDF = async (title, content, language, type) => {
    // 1. Ek temporary div banayein jise hum PDF mein convert karenge
    const element = document.createElement('div');
    
    // 2. Is div ko style karein taaki PDF professional dikhe
    element.innerHTML = `
        <div style="padding: 40px; font-family: Arial, sans-serif; color: #333; line-height: 1.6;">
            <div style="text-align: center; margin-bottom: 20px;">
                <h1 style="color: #643296; margin-bottom: 5px;">Vishwa Vani</h1>
                <p style="color: #787878; font-size: 14px; margin-top: 0;">AI Document Intelligence</p>
                <hr style="border: 0; border-top: 2px solid #643296; margin: 20px 0;" />
            </div>
            
            <h2 style="color: #323232; font-size: 24px; margin-bottom: 10px;">${title}</h2>
            <p style="color: #888; font-size: 12px; margin-bottom: 20px;">
                Type: ${type} | Language: ${language} | Date: ${new Date().toLocaleDateString()}
            </p>
            
            <div style="font-size: 16px; white-space: pre-wrap; word-wrap: break-word;">
                ${content}
            </div>
            
            <div style="margin-top: 50px; border-top: 1px solid #eee; padding-top: 10px; font-size: 10px; color: #aaa; text-align: center;">
                Generated by Vishwa Vani AI
            </div>
        </div>
    `;

    // 3. PDF options set karein
    const opt = {
        margin:       10,
        filename:     `${title.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`,
        image:        { type: 'jpeg', quality: 0.98 },
        html2canvas:  { scale: 2, useCORS: true },
        jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' }
    };

    // 4. PDF generate aur download karein
    try {
        await html2pdf().set(opt).from(element).save();
        return true;
    } catch (error) {
        console.error('PDF Export Error:', error);
        alert("PDF download fail ho gaya: " + error.message);
        return false;
    }
};